<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notebook Observation #{{ $observation->id }}</title>
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; font-family: Arial, Helvetica, sans-serif; color: #0f172a; background: #f8fafc; }
        .shell { max-width: 1280px; margin: 0 auto; padding: 18px; }
        .toolbar { display: flex; gap: 10px; margin-bottom: 14px; }
        .btn { display: inline-flex; align-items: center; justify-content: center; min-height: 38px; padding: 8px 14px; border: 1px solid #cbd5e1; border-radius: 10px; background: #fff; color: #0f172a; font-weight: 600; text-decoration: none; cursor: pointer; }
        .sheet { background: #fff; border: 1px solid #e2e8f0; border-radius: 16px; padding: 20px; }
        .header { border-bottom: 1px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 12px; }
        .title { margin: 0; font-size: 22px; }
        .subtitle { margin: 5px 0 0; color: #334155; font-size: 14px; }
        .meta { margin-bottom: 12px; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; font-size: 12px; color: #334155; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th, td { border: 1px solid #cbd5e1; padding: 6px 7px; text-align: left; vertical-align: top; }
        th { background: #e0ecff; color: #1e3a8a; text-transform: uppercase; letter-spacing: 0.03em; font-size: 10px; }
        .signature { margin-top: 34px; display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 40px; }
        .signature-line { margin-top: 44px; border-bottom: 1px solid #64748b; }
        @media print {
            body { background: #fff; }
            .shell { max-width: none; padding: 0; }
            .toolbar { display: none !important; }
            .sheet { border: none; border-radius: 0; padding: 0; }
            @page { size: A4 portrait; margin: 10mm; }
        }
    </style>
</head>
<body>
    <div class="shell">
        <div class="toolbar">
            <button type="button" onclick="window.print()" class="btn">Print</button>
            <a href="{{ route('principal.notebook-observations.show', $observation->id) }}" class="btn">Back</a>
        </div>

        <section class="sheet">
            <header class="header">
                <h1 class="title">Notebook Observation Form</h1>
                <p class="subtitle">Notebook review and maintenance checklist report.</p>
            </header>

            <div class="meta">
                <div><strong>Observed Teacher:</strong> {{ $observation->observedTeacher?->name ?? '-' }}</div>
                <div><strong>Observer:</strong> {{ $observation->observer?->name ?? '-' }}</div>
                <div><strong>Session:</strong> {{ $observation->session }}</div>
                <div><strong>Date:</strong> {{ optional($observation->observation_date)->format('d M Y') ?: '-' }}</div>
                <div><strong>Class/Section:</strong> {{ trim(($observation->classRoom?->name ?? '').' '.($observation->classRoom?->section ?? '')) ?: '-' }}</div>
                <div><strong>Subject:</strong> {{ $observation->subject?->name ?? '-' }}</div>
                <div><strong>Total Students:</strong> {{ $observation->total_students ?? '-' }}</div>
                <div><strong>Performance:</strong> {{ number_format((float) ($observation->performance_score ?? 0), 2) }}%</div>
                <div><strong>Provided:</strong> {{ $observation->notebooks_provided ?? '-' }}</div>
                <div><strong>Covered:</strong> {{ $observation->covered_notebooks ?? '-' }}</div>
                <div><strong>Uncovered:</strong> {{ $observation->uncovered_notebooks ?? '-' }}</div>
                <div><strong>Well Maintained:</strong> {{ $observation->well_maintained ?? '-' }}</div>
                <div><strong>Total Yes:</strong> {{ (int) $observation->total_yes }}</div>
                <div><strong>Total No:</strong> {{ (int) $observation->total_no }}</div>
                <div><strong>Generated By:</strong> {{ $generated_by?->name ?? '-' }}</div>
                <div><strong>Generated At:</strong> {{ $generated_at->format('d M Y h:i A') }}</div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>Checklist Item</th>
                        <th>Response</th>
                        <th>Comments</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($observation->items as $item)
                        <tr>
                            <td>{{ $item->checklist_text }}</td>
                            <td>{{ strtoupper((string) $item->response) }}</td>
                            <td>{{ $item->comments ?: '-' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3" style="text-align:center;padding:20px;">No checklist rows.</td></tr>
                    @endforelse
                </tbody>
            </table>

            <table style="margin-top:12px;">
                <tbody>
                    <tr><th style="width:180px;">General Comments</th><td>{{ $observation->general_comments ?: '-' }}</td></tr>
                    <tr><th>Teacher Comments</th><td>{{ $observation->teacher_comments ?: 'Pending teacher comment.' }}</td></tr>
                </tbody>
            </table>

            <div class="signature">
                <div>
                    <div style="font-size:12px;color:#334155;font-weight:700;">Observer Signature</div>
                    <div class="signature-line"></div>
                </div>
                <div>
                    <div style="font-size:12px;color:#334155;font-weight:700;">Teacher Signature</div>
                    <div class="signature-line"></div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>
