<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lesson Observation #{{ $observation->id }}</title>
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; font-family: Arial, Helvetica, sans-serif; color: #0f172a; background: #f8fafc; }
        .shell { max-width: 1280px; margin: 0 auto; padding: 18px; }
        .toolbar { display: flex; gap: 10px; margin-bottom: 14px; }
        .btn { display: inline-flex; align-items: center; justify-content: center; min-height: 38px; padding: 8px 14px; border: 1px solid #cbd5e1; border-radius: 10px; background: #fff; color: #0f172a; font-weight: 600; text-decoration: none; cursor: pointer; }
        .sheet { background: #fff; border: 1px solid #e2e8f0; border-radius: 16px; padding: 20px; }
        .header { border-bottom: 1px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 12px; }
        .title { margin: 0; font-size: 22px; }
        .subtitle { margin: 5px 0 0; color: #334155; font-size: 14px; }
        .meta { margin-bottom: 12px; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; font-size: 12px; color: #334155; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th, td { border: 1px solid #cbd5e1; padding: 6px 7px; text-align: left; vertical-align: top; }
        th { background: #e0ecff; color: #1e3a8a; text-transform: uppercase; letter-spacing: 0.03em; font-size: 10px; }
        .section-title { margin: 14px 0 8px; font-size: 13px; font-weight: 700; color: #1e293b; }
        .signature { margin-top: 34px; display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 40px; }
        .signature-line { margin-top: 44px; border-bottom: 1px solid #64748b; }
        @media print {
            body { background: #fff; }
            .shell { max-width: none; padding: 0; }
            .toolbar { display: none !important; }
            .sheet { border: none; border-radius: 0; padding: 0; }
            @page { size: A4 portrait; margin: 10mm; }
        }
    </style>
</head>
<body>
    @php
        $routeBase = $routeBase ?? 'principal.lesson-observations';
    @endphp
    <div class="shell">
        <div class="toolbar">
            <button type="button" onclick="window.print()" class="btn">Print</button>
            <a href="{{ route($routeBase.'.show', $observation->id) }}" class="btn">Back</a>
        </div>

        <section class="sheet">
            <header class="header">
                <h1 class="title">KORT Lesson Observation Form</h1>
                <p class="subtitle">Observation record for teacher performance and follow-up.</p>
            </header>

            <div class="meta">
                <div><strong>Observed Teacher:</strong> {{ $observation->observedTeacher?->name ?? '-' }}</div>
                <div><strong>Observer:</strong> {{ $observation->observer?->name ?? '-' }}</div>
                <div><strong>Session:</strong> {{ $observation->session }}</div>
                <div><strong>Date:</strong> {{ optional($observation->observation_date)->format('d M Y') ?: '-' }}</div>
                <div><strong>Class/Section:</strong> {{ trim(($observation->classRoom?->name ?? '').' '.($observation->classRoom?->section ?? '')) ?: '-' }}</div>
                <div><strong>Subject/Topic:</strong> {{ $observation->subject_topic ?: '-' }}</div>
                <div><strong>No. of Students:</strong> {{ $observation->no_of_students ?? '-' }}</div>
                <div><strong>Overall Judgment:</strong> {{ $observation->overall_judgment ?: '-' }}</div>
                <div><strong>Total Marks:</strong> {{ number_format((float) $observation->total_marks, 2) }} / {{ number_format((float) $observation->max_marks, 2) }}</div>
                <div><strong>Performance:</strong> {{ number_format((float) ($observation->performance_score ?? 0), 2) }}%</div>
                <div><strong>Progress:</strong> {{ $observation->progress_percentage !== null ? number_format((float) $observation->progress_percentage, 2).'%' : '-' }}</div>
                <div><strong>Generated By:</strong> {{ $generated_by?->name ?? '-' }} ({{ $generated_at->format('d M Y h:i A') }})</div>
            </div>

            <p class="section-title">Checklist Standards</p>
            <table>
                <thead>
                    <tr>
                        <th>Area</th>
                        <th>Standard</th>
                        <th>Mark</th>
                        <th>Comments</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($observation->items as $item)
                        <tr>
                            <td>{{ $item->area }}</td>
                            <td>{{ $item->standard_text }}</td>
                            <td>{{ $item->mark }} / {{ $item->max_mark }}</td>
                            <td>{{ $item->comments ?: '-' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4" style="text-align:center;padding:20px;">No checklist rows.</td></tr>
                    @endforelse
                </tbody>
            </table>

            <p class="section-title">Narrative Notes</p>
            <table>
                <tbody>
                    <tr><th style="width:180px;">Learning Objectives</th><td>{{ $observation->learning_objectives ?: '-' }}</td></tr>
                    <tr><th>Previous Targets</th><td>{{ $observation->previous_targets ?: '-' }}</td></tr>
                    <tr><th>What Went Well</th><td>{{ $observation->what_went_well ?: '-' }}</td></tr>
                    <tr><th>Even Better If</th><td>{{ $observation->even_better_if ?: '-' }}</td></tr>
                    <tr><th>Teacher Comments</th><td>{{ $observation->teacher_comments ?: 'Pending teacher comment.' }}</td></tr>
                </tbody>
            </table>

            <div class="signature">
                <div>
                    <div style="font-size:12px;color:#334155;font-weight:700;">Observer Signature</div>
                    <div class="signature-line"></div>
                </div>
                <div>
                    <div style="font-size:12px;color:#334155;font-weight:700;">Teacher Signature</div>
                    <div class="signature-line"></div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>
